# Generated by Django 6.0.2 on 2026-03-04 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body_metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleBaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi_category', models.CharField(max_length=50)),
                ('bfp_category', models.CharField(max_length=50)),
                ('lean_mass_category', models.CharField(max_length=50)),
                ('fat_mass_category', models.CharField(max_length=50)),
                ('bmr_category', models.CharField(max_length=50)),
                ('tdee_category', models.CharField(max_length=50)),
                ('fat_to_lose_status', models.CharField(max_length=50)),
                ('ideal_bfp_deviation', models.CharField(max_length=50)),
                ('primary_pattern', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=50)),
                ('metabolic_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('body_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body_metrics.bodymetrics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_base_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
