# Generated by Django 6.0.2 on 2026-03-04 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('sleep_duration', models.FloatField()),
                ('exercise_frequency', models.IntegerField()),
                ('smoking_status', models.BooleanField()),
                ('bed_time', models.TimeField()),
                ('caffeine_mg', models.FloatField()),
                ('alcohol_grams', models.FloatField()),
                ('awakenings', models.IntegerField()),
                ('predicted_efficiency', models.IntegerField(blank=True, null=True)),
                ('efficiency_label', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
