# Generated by Django 6.0.2 on 2026-03-04 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('activity_factor', models.FloatField()),
                ('bmi', models.FloatField()),
                ('body_fat_percentage', models.FloatField()),
                ('fat_mass', models.FloatField()),
                ('lean_mass', models.FloatField()),
                ('ideal_body_fat_percentage', models.FloatField()),
                ('fat_to_lose', models.FloatField()),
                ('bmr', models.FloatField()),
                ('tdee', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('body_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body_profiles.bodyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
