# Generated by Django 6.0.2 on 2026-03-04 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=50)),
                ('program_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_recommended.goal')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_recommended.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('equipment', models.CharField(max_length=50)),
                ('program_length', models.IntegerField()),
                ('time_per_workout', models.CharField(max_length=100)),
                ('total_exercises', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goals', models.ManyToManyField(related_name='programs', to='sport_recommended.goal')),
                ('levels', models.ManyToManyField(related_name='programs', to='sport_recommended.level')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sport_recommended.recommendationrequest')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_recommended.trainingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('number_of_exercises', models.IntegerField()),
                ('exercise_name', models.CharField(max_length=255)),
                ('sets', models.CharField(max_length=50)),
                ('reps_display', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='sport_recommended.trainingprogram')),
            ],
        ),
    ]
