# Generated by Django 6.0.2 on 2026-03-04 06:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('none', 'Not Specified')], default='none', max_length=10)),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('neck_circumference', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('waist_circumference', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hip_circumference', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('activity_level', models.CharField(choices=[('none', 'None'), ('very_low', 'Very Low'), ('light', 'Light'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
